### ISSUE TITLE
EOLR trainer doesn't filter 2a/0 correctly

### ISSUE THREAD

**Issue by TomasKralCZ** [onionhoney/roux-trainers#2]
Hello there ! First of all, this is a great app, thank you very much for making it so nice to use !

There's one problem with the EOLR trainer, which is when I select 2a/0, it shows other cases as well.
The filter works for all other cases, but not this one.

I don't know how much info you need, but I'm running Firefox 86.0.
 
![Screenshot_20210309_180653](https://user-images.githubusercontent.com/23663355/110509198-24aa7280-8102-11eb-875d-a2435681426f.png)

**Comment by onionhoney** [comment]
Hi. Thank you a lot for the bug report! Turns out I completely missed the handling of this case (2a/0). This has been fixed in commit https://github.com/onionhoney/roux-trainers/commit/d71a995e9374c6b143bd0d32653666c0e65de3d7.
